from langgraph.graph import StateGraph, START, END
from langgraph.constants import Send
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from pydantic import BaseModel, Field
from typing import TypedDict, List, Annotated, Literal, Dict
from pathlib import Path
import operator
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- DATA MODELS ---

class Task(BaseModel):
    """Represents a single section of the blog post."""
    id: int = Field(description="Unique identifier for the section (used for ordering)")
    title: str = Field(description="The heading for this blog section")
    goal: str = Field(description="A one-sentence description of the intended reader takeaway")
    bullets: List[str] = Field(
        description="3 to 5 concrete, specific subpoints to cover in this section",
        min_length=3,
        max_length=5
    )
    target_words: int = Field(
        description="Target word count for this section (120-450)",
        ge=120,
        le=450
    )
    section_type: Literal["intro", "core", "examples", "checklist", "common_mistakes", "conclusion"] = Field(
        description="Technically enforced type of content for this section"
    )

class Plan(BaseModel):
    """The full blog plan generated by the orchestrator."""
    blog_title: str
    audience: str
    tone: str
    tasks: List[Task]

# --- STATE DEFINITION ---

class State(TypedDict):
    """The shared memory/state of the LangGraph agent."""
    topic: str
    plan: Plan
    # We use a dictionary for sections to ensure we can order them by ID regardless of finish order
    sections: Annotated[Dict[int, str], operator.ior]
    final: str

# --- LLM SETUP ---

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)

# --- NODES ---

def orchestrator(state: State):
    """Master node that reads the topic, generates a structured Plan."""
    print(f"--- ORCHESTRATOR: Planning for topic '{state['topic']}' ---")
    
    system_prompt = (
        "You are a Senior Technical Writer and Developer Advocate at a top-tier tech company. "
        "Your task is to plan a high-impact, technical blog post on a given topic. "
        "The plan must be rigorous, practical, and highly structured to avoid vague content.\n\n"
        "HARD REQUIREMENTS:\n"
        "1. Produce 5 to 7 sections (tasks) using the Plan model.\n"
        "2. Each section MUST have a UNIQUE sequential ID (1, 2, 3...) for ordering.\n"
        "3. Each section MUST have a goal, 3-5 concrete bullets, and a target word count.\n"
        "4. Follow the logical flow: Problem → Intuition → Approach → Implementation → Trade-offs → Testing → Conclusion.\n"
        "5. The plan must cover at least one of: code examples, edge cases, or debugging tips.\n"
    )
    
    # Force structured output
    structured_llm = llm.with_structured_output(Plan)
    
    # Generate the plan
    plan = structured_llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Generate a detailed technical blog plan for the topic: {state['topic']}")
    ])
    
    return {"plan": plan}

def worker(payload: dict):
    """Parallel worker node that writes a single section of the blog."""
    task: Task = payload["task"]
    topic: str = payload["topic"]
    plan: Plan = payload["plan"]
    
    print(f"--- WORKER: Writing section {task.id}: '{task.title}' ---")
    
    # Format bullets for the prompt
    bullets_str = "\n".join([f"- {b}" for b in task.bullets])
    
    system_prompt = (
        "You are a Senior Technical Writer. Write ONE section of a technical blog post in Markdown.\n\n"
        "HARD CONSTRAINTS:\n"
        f"1. Follow the Goal: {task.goal}\n"
        f"2. Stay within word count range: {task.target_words} words ±15%.\n"
        "3. Output ONLY the section content. Start with a '## [Title]' heading.\n"
    )
    
    human_message = (
        f"Main Topic: {topic}\n"
        f"Section Title: {task.title}\n"
        f"Goal: {task.goal}\n"
        f"Required Bullets:\n{bullets_str}"
    )
    
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=human_message)
    ])
    
    # Return dictionary indexed by task ID to preserve order in the reducer
    return {"sections": {task.id: response.content}}

def fanout(state: State):
    """Dispatcher function that launches parallel workers for each task."""
    print(f"--- FANOUT: Launching {len(state['plan'].tasks)} parallel writers ---")
    return [
        Send("worker", {"task": task, "topic": state["topic"], "plan": state["plan"]})
        for task in state["plan"].tasks
    ]

def reducer(state: State):
    """Final node that compiles sections in CORRECT order and saves the blog."""
    print("--- REDUCER: Compiling final blog post ---")
    
    title = state["plan"].blog_title
    
    # Sort sections by their ID to ensure the final blog is in the planned order
    sorted_ids = sorted(state.get("sections", {}).keys())
    ordered_content = [state["sections"][i] for i in sorted_ids]
    
    compiled_body = "\n\n".join(ordered_content)
    final_markdown = f"# {title}\n\n{compiled_body}"
    
    # Save to file
    safe_name = "".join([c if c.isalnum() else "_" for c in title.lower()])
    file_path = Path(f"{safe_name}.md")
    file_path.write_text(final_markdown)
    
    print(f"--- DONE: Blog post saved to '{file_path}' ---")
    return {"final": final_markdown}

# --- GRAPH CONSTRUCTION ---

workflow = StateGraph(State)

workflow.add_node("orchestrator", orchestrator)
workflow.add_node("worker", worker)
workflow.add_node("reducer", reducer)

workflow.add_edge(START, "orchestrator")
workflow.add_conditional_edges("orchestrator", fanout, ["worker"])
workflow.add_edge("worker", "reducer")
workflow.add_edge("reducer", END)

app = workflow.compile()

# --- EXECUTION ---

if __name__ == "__main__":
    import os
    
    if not os.getenv("OPENAI_API_KEY") or "your_openai_api_key_here" in os.getenv("OPENAI_API_KEY"):
        print("\n[!] ERROR: Please set your OPENAI_API_KEY in the .env file before running.")
    else:
        topic = "History of Sound and Music generation using AI"
        print(f"\n--- STARTING AGENT for topic: '{topic}' ---")
        
        # Initialize state with an empty dictionary for sections
        initial_state = {"topic": topic, "sections": {}}
        result = app.invoke(initial_state)
        
        # Verify file save
        title = result["plan"].blog_title
        safe_name = "".join([c if c.isalnum() else "_" for c in title.lower()])
        print(f"\n[✓] Success! Markdown file saved as: {safe_name}.md")
